### ISSUE TITLE
Patcher crashes when the first option is selected

### ISSUE THREAD

**Issue by RyanTheInkling** [WiiLink24/WiiLink24-Patcher#10]
Whenever I start up the patcher and reach the point where I start the installation process, it crashes after the word Patching appears. What is causing this issue, and how do I fix it?
![image](https://user-images.githubusercontent.com/41594800/121790933-c9c16500-cba1-11eb-91a3-dc535732ed02.png)

**Comment by CatfyNinja** [comment]
The same thing happens to me

**Comment by spotlightishere** [comment]
Several versions have passed since this issue - going to close, as hopefully this has been resolved in newer versions.

If the issue persists, please create a new issue describing any errors you receive. Thank you!
