### ISSUE TITLE
WiiRoom hash miss match

### ISSUE THREAD

**Issue by Parker2991** [WiiLink24/WiiLink24-Patcher#100]
whenever i try to install the wii room wad it fails because of the hash being miss matched im using a wii running v4.3u

**Comment by AyeItsHarry** [comment]
Can you please try again with the latest patcher version and let us know if the issue still occurs?

**Comment by Parker2991** [comment]
i did a few weeks back when remodding my wii and it worked

**Comment by AyeItsHarry** [comment]
glad to hear that!
