### ISSUE TITLE
Task: Downloading yawmME

### ISSUE THREAD

**Issue by EliasSkeppstedt** [WiiLink24/WiiLink24-Patcher#103]
```
WiiLink Patcher v2.0.3 - (c) 2024 WiiLink Team
========================================================================================================================

An error has occurred.

ERROR DETAILS:

 * Task:  Downloading yawmME
 * Message: Failed to download yawmME from https://hbb1.oscwii.org/api/v3/contents/yawmME/icon.png to
apps\yawmME\icon.png
 * Exit code: 522

Please open an issue on our GitHub page (https://github.com/WiiLink24/WiiLink24-Patcher/issues) and describe the
error you encountered. Please include the error details above in your issue.

Press any key to go back to the main menu...
```
I first had yawME on the sd card, and i got the same error, then i tried after removing yawME, but then i got this error again.
I chose
Express instalation, 1
Europe, 2
Yes, 1
Translated, 1
English, 1
Standard, 1
vWii, 1
Start with SD card, 1
Keep WAD folder, 2

**Comment by PablosCorner** [comment]
Open Shop Channel's servers seem to be a bit slow tonight, I imagine once it clears up it'll work as expected.

**Comment by EliasSkeppstedt** [comment]
Ill try again later. Ill update the results then 😄

**Comment by EliasSkeppstedt** [comment]
Update. I tried to run it as administrator (and without the sd card in my PC) and it downloaded the files.
So i put the apps and WAD folder in the root of my sd card and following the guide, i should install a wud file called `WiiLink SPD (vWii).wad` although I didnt recive such file from the download. Is this a separate wud file that i need to download elsewhere?
