### ISSUE TITLE
Failed download attempt on the WiiLink patcher v2.0.3

### ISSUE THREAD

**Issue by thatonelilguyfromtechtok** [WiiLink24/WiiLink24-Patcher#110]
this just showed up: 
An error has occurred.

ERROR DETAILS:

 * Task:  Downloading 0001000148415050
 * Message: Downloading Content Failed:
An exception occurred during a WebClient request.
 * Exit code: -2146233088

**Comment by Niavy64** [comment]
Same error for me and the News Channel

__________________

An error has occurred.

ERROR DETAILS:

 * Task:  Downloading 0001000248414750
 * Message: Downloading Content Failed:
An exception occurred during a WebClient request.
 * Exit code: -2146233088

Please open an issue on our GitHub page (https://github.com/WiiLink24/WiiLink24-Patcher/issues) and describe the
error you encountered. Please include the error details above in your issue.

Press any key to go back to the main menu...

**Comment by AyeItsHarry** [comment]
Can you please try again with the latest patcher version and let us know if the issue still occurs?
