### ISSUE TITLE
It doesnt have option for windows

### ISSUE THREAD

**Issue by Erod0006** [WiiLink24/WiiLink24-Patcher#111]

**Comment by SnivySquid65** [comment]
I think I can help!

In releases, there is a .exe file called `WiiLinkPatcher_Windows_v203.exe`.  Click [`here`](https://github.com/WiiLink24/WiiLink24-Patcher/releases/download/v2.0.3/WiiLinkPatcher_Windows_v203.exe) to download it.
If the .exe is not working, you could try the Linux version!  Use bash to run the file.  I recommend Windows users use the Microsoft store to install Visual Studio Code, then use the bash terminal to run it from there.  Simply do `cd Downloads` then run `./WiiLinkPatcher_Linux-x64_v203`!  The process is streamlined from there.

Good Luck!

**Comment by AyeItsHarry** [comment]
fyi, the linux version isn't bash, but compiled c#, so that wouldn't work. you'd have to use wsl to use the linux version. @Erod0006, if you're still having issues, i'd recommend joining the wiilink discord server for further support - [discord.gg/wiilink](https://discord.gg/wiilink)

**Comment by SnivySquid65** [comment]
Sorry, I haven't used Windows in like, 4 years, so I have no clue.  Once again, I apologize for the confusion.
