### ISSUE TITLE
Tryna install this on dolphin

### ISSUE THREAD

**Issue by thegameraudi2023** [WiiLink24/WiiLink24-Patcher#116]
WiiLink Patcher v2.0.3 - (c) 2024 WiiLink Team
========================================================================================================================

An error has occurred.

ERROR DETAILS:

 * Task:  Downloading 0001000148415445
 * Message: Unable to verify any online NUS server!
 * Exit code: -2146233088

Please open an issue on our GitHub page (https://github.com/WiiLink24/WiiLink24-Patcher/issues) and describe the
error you encountered. Please include the error details above in your issue.

Press any key to go back to the main menu...

what

**Comment by thegameraudi2023** [comment]
also when i try to put the riilink24 DNS this happens when testing(even when trying to connect with a normal internet that isn't riilink24 DNS)
Error Code: 101232
There is a problem with
the WiiConnect24 service.
Please try again later.

**Comment by thegameraudi2023** [comment]
i fixed the nus server thing but the internet is still not working

**Comment by AyeItsHarry** [comment]
please follow up to date setup instructions [here](https://wiilink24.com/guide/dolphin)

**Comment by AyeItsHarry** [comment]
they don't include dns or wii mail, as these services don't work in dolphin. you can technically use the dns by changing your computer's internet settings, but this would significantly slow down your internet connection
