### ISSUE TITLE
Update the guides and pages!

### ISSUE THREAD

**Issue by tritstrits-televisar** [WiiLink24/WiiLink24-Patcher#119]
Edit: *Miraculously my food channel just got fixed RIGHT as I finished writing this, now it just asks for an address!
Yall gotta update the guide pages, cause I spent like 3 or 4 hours trying to redownload everything after using vwii decaffeinator, some files aren't even provided in wiilink anymore like wiilink SPD or ios31 patcher! Why download a legacy launcher when you have a newer one? Then the error codes page has errors that don't line up with the codes on the other separate install guides for each channel! Like for example error 107425 is not the same as the error provided on the news channel! You gotta download a patched ios31 to use it! And it also doesn't have errors for things like error 285502 shows on photo print channel, _*and the food channel is asking to update the vwii?!_ Kirby channel doesn't even work anymore!

**Comment by AyeItsHarry** [comment]
this is on the wrong repo, and all the guides are fine. spd has been renamed to wiilink address settings, and a patched ios31 is no longer needed. please follow the up to date instructions at https://wiilink.ca/guide/install

your news channel error comes from using an outdated wad, if you install a new wad from the latest patcher version, it will work without a patched ios31
