### ISSUE TITLE
Forecast, News and photo channel's wads are not installing, vWii

### ISSUE THREAD

**Issue by Mudkip812** [WiiLink24/WiiLink24-Patcher#122]
So I tried to Install these wads in YAWM ModMii Edition but they give me an error about the IOS space being a stub,and its weird because i don't even have those channels on my vWii Menu, so please i need an answear to fix that

**Comment by AyeItsHarry** [comment]
Please join the [WiiLink Discord](https://discord.gg/wiilink) for support.

**Comment by Mudkip812** [comment]
Ok thanks :D
