### ISSUE TITLE
The SPD channel doesn't  load/work on US vWii

### ISSUE THREAD

**Issue by WWIA7062** [WiiLink24/WiiLink24-Patcher#13]
when running the SPD loader it says please install the patcher at Wiilink24.com after trying to install it says its installed correctly on wii mod lite

**Comment by spotlightishere** [comment]
If you reinstall the SPD WAD, does it function?

If not, please try this edit specifically for the vWii and let us know how things function:
[WiiLink24_SPD_vWii__2021-05-16_v4.wad.zip](https://github.com/WiiLink24/WiiLink24-Patcher/files/7118965/WiiLink24_SPD_vWii__2021-05-16_v4.wad.zip)

**Comment by WWIA7062** [comment]
i tryed on both meny times and both versions fail

**Comment by WWIA7062** [comment]
any other ideas?

**Comment by WWIA7062** [comment]
i tried one more time it worked hopefully when demae channel comes out you can add more info in the spd thx for your help and there should be a option for the vwii verson in the patcher soon
