### ISSUE TITLE
Intro Splash still Showing as "WiiRoom" in the latest WiiLink24 patch on Japanese version

### ISSUE THREAD

**Issue by DraconicNEO** [WiiLink24/WiiLink24-Patcher#18]
Hello, I just recently installed the update that supposedly fixed this issue although it only seems to have fixed the Banner, the splash screen (different from the banner, this is the video intro that plays immediately after the [Wii remote screen](https://user-images.githubusercontent.com/44508470/142788134-0f680cbd-2fc0-4e6a-add0-a33c3ec91736.png)[Which on a sidenote is also [messed up](https://user-images.githubusercontent.com/44508470/142788571-e7dae9d1-762a-4b9c-8a7e-a636082d736a.png) on the japanese version]) seems to still have the same issue.

This is what it should look like (as it does in the original without translation patches):
![WiiNoMa Splash](https://user-images.githubusercontent.com/44508470/142787531-a520127f-e6ce-44fe-bfd5-fa0a159875bc.png)

However even in the latest version it's still displaying the patched version even on builds that aren't supposed to be translated.
This is what appears on the latest build of WiiLink24 patches, Japanese version:
![WiiRoom Splash](https://user-images.githubusercontent.com/44508470/142787603-af67dc37-0f8d-497d-bb1d-2468aa6a0dc7.png)

Hopefully this can soon be fixed as this isn't something that can be easily DIY fixed like with the Banner.

**Comment by DraconicNEO** [comment]
> @noahpistilli does this still happen?

Last I tried it still happens.

**Comment by PablosCorner** [comment]
> > @noahpistilli does this still happen?
> 
> Last I tried it still happens.

If you used the latest version of the patcher and ran Wiiの間, does "Wii Room" still show up?

**Comment by tesmite** [comment]
When I downloaded the Japanese version of Wii no Ma using the latest WiiLink Patcher (v2.0.0), this problem did not occur and the Japanese version of Wii no Ma (Wiiの間) remained.
