### ISSUE TITLE
-2011 cant install wad error code please check the root of your sd card!

### ISSUE THREAD

**Issue by lelkasa** [WiiLink24/WiiLink24-Patcher#23]
Hi i use dolphin  how to fix? also i cant install any channels from the wii link 24 patcher!!!
Mon Mar 21 10:27:21 2022
An WAD install error has occurred. /dev/es error code: -2011

Mon Mar 21 10:28:03 2022
An WAD install error has occurred. /dev/es error code: -2011

Mon Mar 21 10:29:21 2022
An WAD install error has occurred. /dev/es error code: -2011

Tue Mar 22 13:27:54 2022
An WAD install error has occurred. /dev/es error code: -2011

Wed Mar 23 21:38:55 2022
An WAD install error has occurred. /dev/es error code: -2011

**Comment by SketchMaster2001** [comment]
You cannot use the Wii Patcher on Dolphin. The guide on https://wii.guide/wiilink clearly states this.

Closing.

**Comment by ljcool2006** [comment]
Is there any clue as to why [the current guide](https://www.wiilink24.com/guide/install/) states that it is applicable to Dolphin?

**Comment by PablosCorner** [comment]
> Is there any clue as to why [the current guide](https://www.wiilink24.com/guide/install/) states that it is applicable to Dolphin?

You might want to open an issue for [this repository](https://github.com/WiiLink24/web).
