### ISSUE TITLE
Remote catalogue of patches

### ISSUE THREAD

**Issue by spotlightishere** [WiiLink24/WiiLink24-Patcher#27]
It would be nice to modify this patcher to eventually support a remote catalogue of patches. One discussed format may be similar to the following upon app open:
```xml
<catalog>
  <title>
    <name>Wii Room - Shop</name>
    <slug>wii-room</slug>
    <version>1025</version>
  </title>
  <title>
    <name>Wii Room - Theatre</name>
    <slug>wii-room</slug>
    <version>770</version>
  </title>
</catalog>
```

From there, a list of patches could be requested for that title.
```xml
<title>
    <patches>
      <base title="000100014843494a" version="1025"/>
      <patch index="1" filename="00000001.patch"/>
      <!-- `language` characteristic has this rule only apply if selected language is English -->
      <patch language="en" index="2" filename="00000002_en.patch"/>
      <!-- Filename can be assumed to be /wii-room/1025/00000002_jp.app -->
      <patch language="jp" index="2" filename="00000002_jp.patch"/>
    </patches>
</title>
```

Of course, we would still need direct WAD support to support [Set Personal Data](https://github.com/WiiLink24/set-personal-data), as we create our own WADs directly to install.

Any insight/suggestions/etc into the format would be appreciated!

**Comment by noahpistilli** [comment]
Wii Patcher was deprecated, closing
