### ISSUE TITLE
An WAD install error has occurred. /dev/es error code: -1027

### ISSUE THREAD

**Issue by FireWall-Programming** [WiiLink24/WiiLink24-Patcher#29]
How do I fix this problem? Is it a problem with the WAD download? any help would be appreciated.
Thanks!

**Comment by FireWall-Programming** [comment]
Fixed it, closing.

**Comment by JKakaofanatiker** [comment]
How did you fix it?

**Comment by FireWall-Programming** [comment]
Uninstall the WAD, then reinstall it.

**Comment by JKakaofanatiker** [comment]
Doesn't work for me.

**Comment by FireWall-Programming** [comment]
I'm not really an expert, but, how did you uninstall?

**Comment by JKakaofanatiker** [comment]
I used Wii Mod Lite and the Wii's own uninstall menu. Both result in the same error.

**Comment by FireWall-Programming** [comment]
I used Wii Mod Lite too, I don't know how to do it, it helped me, did you see the wad in the manager? Try installing it, after you uninstall the wad, if that doesn't work, I can't help you anymore.

**Comment by JKakaofanatiker** [comment]
I tried it and it doesn't help. I hope that it gets fixed soon.

**Comment by Fratze64** [comment]
The wad installs but only on the root of the SD Card so you need to install it then manually over Wii Mod Lite.

**Comment by noahpistilli** [comment]
Wii Patcher was deprecated, closing
