### ISSUE TITLE
When launching WiiLink Patcher, it just takes me back to the home menu

### ISSUE THREAD

**Issue by MarioGaming298** [WiiLink24/WiiLink24-Patcher#32]
Every time I try and launch the WiiLink Patcher channel, it just takes me back to the home menu.

**Comment by ScratchLink24** [comment]
Is your SD Card inserted? If not, Insert your damn SD Card. That's why.

**Comment by ScratchLink24** [comment]
Not apart of the team, Just to tell you. That was how it loaded for me.

**Comment by MarioGaming298** [comment]
hey, I always insert my sd card before I turn on my Wii and I just tried it again on my wii and got the same error still WITH the sd card in there.

**Comment by ScratchLink24** [comment]
Install Priiloader then.

**Comment by MarioGaming298** [comment]
I already have. I also have the region free options enabled

**Comment by ScratchLink24** [comment]
Dude. get a new wii. I cant help you. Get A DAMN NEW WII.

**Comment by oscie57** [comment]
are you sure you installed the correct patcher? theres two variants

**Comment by ScratchLink24** [comment]
and. Your patcher for PC just keeps damn crashing. I keep redownloading and it doesnt help.

**Comment by oscie57** [comment]
the latest one? should work fine

**Comment by spotlightishere** [comment]
@MarioGaming298 When the channel returns you to the system menu, do you encounter an error related to "Address Info"? If so, this is likely informing you to install the latest version of the Set Personal Data channel. You may want to try reinstalling it via the patcher.

If not, can you explain more about what happens? Does the TV output go black, and immediately return to the system menu?

**Comment by MarioGaming298** [comment]
@spotlightishere yeah it goes black but on the top left corner of the screen it says "led to apply patches" and then it takes me back to the home menu

@oscie57 yeah I checked to make sure I downloaded the Wii WAD and not the vWii WAD

**Comment by MarioGaming298** [comment]
i just found out that i had ios61 installed instead of ios58 and now it works lmao
