### ISSUE TITLE
WAD install error on Dolphin using WiiLink Patcher 1.0.7 WAD

### ISSUE THREAD

**Issue by saulfabregwiivc** [WiiLink24/WiiLink24-Patcher#34]
![image](https://user-images.githubusercontent.com/66485640/187699808-5e1ca9ba-de73-46b4-a4b7-eb464bc1f5ee.png)

Here's my log:
```
Wed Aug 31 09:08:58 2022
An WAD install error has occurred. /dev/es error code: -1017

Wed Aug 31 09:09:49 2022
An WAD install error has occurred. /dev/es error code: -1017
```

**Comment by omerien** [comment]
Same error, also on Dolphin, macOS 10.14, Dolphin Beta.

**Comment by TheMasterCoders** [comment]
YOU'RE NOT SUPPOSED TO USE THE WII PATCHER ON DOLPHIN! DO YOU HAVE ANY IDEA HOW UNSAFE THAT IS?!

**Comment by omerien** [comment]
Why would it be ?

**Comment by noahpistilli** [comment]
Wii Patcher was deprecated, closing
