### ISSUE TITLE
A Internet Error has occured.

### ISSUE THREAD

**Issue by ScratchLink24** [WiiLink24/WiiLink24-Patcher#36]
I connected to the Wi-Fi and it always does this. Please just for the love of god release a PC Patcher update.

**Comment by KcrPL** [comment]
It'll be released within 2 next days.

**Comment by ScratchLink24** [comment]
Thank you. My internet just wont work normally without the RC24 DNS entered in.

**Comment by ScratchLink24** [comment]
OK, Update. It crashes on the PC Patcher every damn time. And HELL NO i am not resetting my PC.

**Comment by spotlightishere** [comment]
Please let us know about error you receive when the patcher crashes. Inflammatory remarks are detrimental to us resolving your issue.

**Comment by ScratchLink24** [comment]
It shows no error, just a blink. I run x86 hardware on a 900$ Laptop that fucking crashes on 30% of my software. The blink is usual.

**Comment by spotlightishere** [comment]
It's unlikely we can resolve this issue in a respectful manner. Thank you for reporting.
