### ISSUE TITLE
Demae channel not letting me order 

### ISSUE THREAD

**Issue by lovebug0706** [WiiLink24/WiiLink24-Patcher#49]
Im from the USA here, and it says theres a server error when I put the error through a translator. I also noticed that the demae website is also down. The first image shows the website.
![Screenshot 2023-02-24 3 46 29 PM](https://user-images.githubusercontent.com/34926216/221288184-4ed3b101-f7c7-4f89-bd5a-7b88d6a27593.png)
The second image below this shows the error on the Demae Channel itself. Also its in Japanese when i got the English version.
![IMG_20230224_154447](https://user-images.githubusercontent.com/34926216/221288231-ce06bc20-571a-4f64-aa1f-29c372dd01ce.jpg)
Hopefully you can fix it!
-MacBack

**Comment by PablosCorner** [comment]
As this isn't really an issue with the patcher, I'm gonna close it. However, there will be a fix coming eventually to restore the servers for Demae Domino's, stay tuned at [on our Discord server](https://discord.gg/WiiLink)!
