### ISSUE TITLE
Patcher closes

### ISSUE THREAD

**Issue by mioakiyama1** [WiiLink24/WiiLink24-Patcher#5]
When I ran the patcher, everything worked, but I have one suggestion. When the patcher is done, it just closes, so people might think that it crashed (I thought it crashed until I saw the WAD on my SD card). So maybe add a screen that says the patching is done, and it will automatically close in 30 seconds or something.

But overall, the patcher is really good. Thanks

**Comment by SketchMaster2001** [comment]
I don't like the idea of countdowns as I find them annoying, but I can add something like click any key to close
