### ISSUE TITLE
An error has occurred

### ISSUE THREAD

**Issue by donchippy** [WiiLink24/WiiLink24-Patcher#52]
Hi. I have error to try use patcher
The photo have details.
I use Wiilink patcher 1.0.8 for Wii and vwii
![16777814097067486171548544305416](https://user-images.githubusercontent.com/68165028/222518729-ad8b4d14-b532-4796-bbd5-f3b3c9b17c12.jpg)

**Comment by PablosCorner** [comment]
Sorry, the patcher is not compatible with Windows 7. It requires some programs that Windows 7 does not have. One of them is curl, which you would need to install manually. However, even with curl installed, you would still face problems with Sharpii (another program we use with the patcher). I would either suggest upgrading your Windows version (to either 10 or 11), or switching over to Linux so you could use the Unix patcher.
