### ISSUE TITLE
Patcher crashes and gives an error after starting patching process

### ISSUE THREAD

**Issue by gitandrew07** [WiiLink24/WiiLink24-Patcher#53]
When i start the patching process, it will instantly crash giving error code 60. **_(and no im not using powershell this time.)_**

**Comment by PablosCorner** [comment]
Can I get a screenshot of the error screen?

**Comment by gitandrew07** [comment]
![error](https://user-images.githubusercontent.com/114159505/222835612-83c84fe5-fc20-48a1-bf86-1a967078b33f.png)

**Comment by gitandrew07** [comment]
So, what can i do?

**Comment by PablosCorner** [comment]
![image](https://user-images.githubusercontent.com/20327900/222885391-dd1345dc-7f9f-4707-a4b7-87923e654bfd.png)
So when I looked up the error code, it says it might be an SSL thing. If you have the means, try testing out the patcher on a different network.

**Comment by gitandrew07** [comment]
Pretty cool, Thank you!👍

**Comment by gitandrew07** [comment]
It appears i got another error..
![image](https://user-images.githubusercontent.com/114159505/222948396-dca0be4e-13c5-4958-af65-0ff42cea0fe9.png)

**Comment by PablosCorner** [comment]
Just curious, what is your locale set to? It seems like Batch is really picky and the script doesn't work right if the locale isn't "English (United States)"

**Comment by PablosCorner** [comment]
Okay I pushed another build where I changed around the formatting of some commands to hopefully make it not error out like that. It seemed to work on my end fine, but as I've learned lately, it might not be the case for everyone else, so please do report back if this fixed it.

**Comment by gitandrew07** [comment]
![image](https://user-images.githubusercontent.com/114159505/222951916-fabb6cbd-3a10-4fd6-a4b3-cfb2f263fd32.png)
I already had my language set to English (United States), however with this new push, i get this giant lump of errors.

**Comment by gitandrew07** [comment]
Also when i press any key to exit, like the patcher asks to, it gives more errors and then goes to the "What are we doing today?" screen.

**Comment by PablosCorner** [comment]
Oh my.. yeah I didn't expect that at all. I didn't think Batch would be this unpredictable when it comes to how Windows is set up in other regions. Honestly, it makes me want to remake this whole thing in a proper programming language so it'll at least work the same for everyone.

**Comment by gitandrew07** [comment]
So... what can i do in conclusion?

**Comment by PablosCorner** [comment]
For now, I would say for now nothing much until I can port it to a proper programming language. Or you could try out the Unix Patcher on a Linux or macOS machine (or virtual machine for Linux), that one seems a lot more stable.

**Comment by PablosCorner** [comment]
If you're interested in trying a new (potential) replacement for the Batch script, check this branch out.
[https://github.com/WiiLink24/WiiLink24-Patcher/tree/csharp-ver](https://github.com/WiiLink24/WiiLink24-Patcher/tree/csharp-ver)

**Comment by gitandrew07** [comment]
oh my god i think its working.

**Comment by gitandrew07** [comment]
im running the C Sharp patcher now

**Comment by gitandrew07** [comment]
![image](https://user-images.githubusercontent.com/114159505/223806377-20c84b4f-a8e5-48ca-83bc-fcc500b428cb.png)
LETS GO IT WORKED!

**Comment by PablosCorner** [comment]
I'm glad to hear that! In that case, I'll consider this issue resolved.
