### ISSUE TITLE
Wiilink shuts off when it starts patching

### ISSUE THREAD

**Issue by d1ad0g3** [WiiLink24/WiiLink24-Patcher#55]
When I start the patcher everything runs fine but when I start patching it it shows for a second and then just crashes with no error or anything. It shows 2 files WAD and Wiilink Patcher folder. But it doesn't have any wads in the WAD folder and its just empty. I've tried almost everything but I can't figure it out.

**Comment by PablosCorner** [comment]
If you're interested in trying a new (potential) replacement for the Batch script, check this branch out.
[https://github.com/WiiLink24/WiiLink24-Patcher/tree/csharp-ver](https://github.com/WiiLink24/WiiLink24-Patcher/tree/csharp-ver)

**Comment by PablosCorner** [comment]
No response in a while, gonna close
