### ISSUE TITLE
Patcher doesn't work with USB SD Card Adapter

### ISSUE THREAD

**Issue by Hendo16** [WiiLink24/WiiLink24-Patcher#57]
I've tried using your windows patcher with a USB SD Card adapter but it can't find the adapter, and even when I give it my drive letter it says it's not a valid drive letter.

**Comment by gitandrew07** [comment]
Try patching the files directly on your pc then put the files on your sd

**Comment by PablosCorner** [comment]
Gonna close due to inactivity, let me know though if it works on v1.1.0 though!
