### ISSUE TITLE
Is the patcher supposed to look like this? 

### ISSUE THREAD

**Issue by dovy64** [WiiLink24/WiiLink24-Patcher#58]
I downloaded it from the link and it looks like this. I'm on Windows 7 (bad laptop)
![image](https://user-images.githubusercontent.com/76756533/225693345-65ea2b93-f992-4cba-8116-2c4c9ee268ca.png)

**Comment by dovy64** [comment]
Also when i put in my sd card it crashes

**Comment by PablosCorner** [comment]
Windows 7 isn't supported in this version of the patcher anymore. The programs and formatting we use for the patcher script don't work on it. I'd recommend either upgrading at least to Windows 10, or trying the patcher on Linux.
