### ISSUE TITLE
Wiilink Patcher Experimental C# version error code

### ISSUE THREAD

**Issue by MasterGamer423** [WiiLink24/WiiLink24-Patcher#59]
While the patcher downloading the files, it gave this error message:

An error has occurred.

ERROR DETAILS:
 * Task: Downloading and extracting stuff for Wii no Ma
 * Command: WiiLink_Patcher\Sharpii.exe nusd -id 000100014843494a -o unpack\000100014843494a.wad -wad -q
 * Exit code: 16014

Please open an issue on our GitHub page (https://github.com/WiiLink24/WiiLink24-Patcher/issues) and describe the
issue you're having.

Press any key to go back to the main menu...

**Comment by PablosCorner** [comment]
Which version of the patcher were you using?

**Comment by MasterGamer423** [comment]
The latest one (v1.1.0 Build 3)

**Comment by PablosCorner** [comment]
Hm, that's bizarre. I was able to run it fine. See if your antivirus is somehow screwing with the patcher or the programs it uses for patching (like Sharpii and Xdelta).

**Comment by PablosCorner** [comment]
Issue mitigated as of commit `e3257df`
