### ISSUE TITLE
Getting error with UNIX patcher

### ISSUE THREAD

**Issue by realicraft** [WiiLink24/WiiLink24-Patcher#6]
When I try to use the UNIX version of the patcher it fails to finish patching, with the following error message:
```
ERROR DETAILS:
        * Task: Patching Wii no Ma
        * Command: ./WiiLink_Patcher/Sharpii wad -u WiiLink_Patcher/${1}/${2}v1025.wad WiiLink_Patcher/${1} -q
        * Line: 17
        * Exit code: 3
```
What's the cause of this, and how do I fix it? If it's of any use, I'm using a Raspberry Pi 4 with Raspbian to run the patcher.

**Comment by SketchMaster2001** [comment]
Fixed in Latest update.
