### ISSUE TITLE
"The system cannot write to the specific device." is the error i'm getting with and sd card or not

### ISSUE THREAD

**Issue by gu1d1** [WiiLink24/WiiLink24-Patcher#60]
I am using Windows 7 if that's an issue IDK

**Comment by PablosCorner** [comment]
Windows 7 isn't supported anymore for WiiLink Patcher, please either upgrade to Windows 10 (at the minimum), or use the Unix Patcher (or Linux/Mac version of the C# patcher) on Linux.

**Comment by gu1d1** [comment]
Could i use a previous patcher?

**Comment by ed0nkey** [comment]
no

**Comment by gu1d1** [comment]
What would happen if i converted the bat file to exe
