### ISSUE TITLE
The temporary file host is dead

### ISSUE THREAD

**Issue by Naim2000** [WiiLink24/WiiLink24-Patcher#69]
![image](https://github.com/WiiLink24/WiiLink24-Patcher/assets/44107089/08ef374f-12b4-42b5-a55f-486b4556daaf)
![image](https://github.com/WiiLink24/WiiLink24-Patcher/assets/44107089/7bfabfa0-ed52-4117-a330-acfe947257c7)

**Comment by PablosCorner** [comment]
I'm looking into it, the site where I usually host my files seems to be down.

**Comment by PablosCorner** [comment]
Fixed as of **v1.1.2h1**
