### ISSUE TITLE
Error with Unix patcher on Mac

### ISSUE THREAD

**Issue by HilbertIdeals5** [WiiLink24/WiiLink24-Patcher#7]
Whenever I run the WiiLink24 patcher for Unix on Mac, it brings up this error:

ERROR DETAILS:
	* Task: Patching Wii no Ma
	* Command: ./WiiLink_Patcher/Sharpii nusd -id ${2} -o 
WiiLink_Patcher/${1} -wad -q
	* Line: 15
	* Exit code: 126

I've tried the latest version in Releases, as well as the latest version in the master branch, and they've both shown this same error on every try. Also, the produced WAD and apps/wiimodlite folders are both empty. I'm running this on macOS Big Sur, if that helps.

**Comment by SketchMaster2001** [comment]
The the patcher download Sharpii? Because it works perfectly fine on my Intel MacBook Pro running Big Sur

**Comment by HilbertIdeals5** [comment]
It looks like it did, there's a folder called "WiiLink_Patcher" that contains:

- Sharpii <-- it calls this a "Unix Executable File"
- WiinoMa_1.delta
- WiinoMa_2.delta
- WiinoMa_tik.delta
- WiinoMa_tmd.delta

**Comment by SketchMaster2001** [comment]
Is your Mac the new M1 or an Intel? If it is M1, my latest release should have fixed it.

**Comment by HilbertIdeals5** [comment]
Mine is the M1.

**Comment by SketchMaster2001** [comment]
Try now

**Comment by HilbertIdeals5** [comment]
Yaaaaay, it runs now :D
And it worked!!! *jumps up and down*

**Comment by SketchMaster2001** [comment]
Closing then ahhhh
