### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by Bananapeelgaming** [WiiLink24/WiiLink24-Patcher#70]
I'm trying to download willing but every time I try to it shows me this.

An error has occurred.

ERROR DETAILS:
	* Task: Downloading patches
	* Command: curl --create-dirs -f -s -o WiiLink_Patcher/Sharpii 
"${FilesHostedOnPablo}/Sharpii/sharpii(${sys})"
	* Line: 677
	* Exit code: 22
	
Does anyone have a fix? I'm using version 1.08 because newer ones don't work with MACOS I don't think.

**Comment by PablosCorner** [comment]
The site it's trying to access is down, and I don't really provide support for the older `.bat/.sh` scripts anymore. I can however try to solve the issue of you not being able to open the current versions of the patcher on your Mac.
