### ISSUE TITLE
Forecast (All Versions, USA, PAL, and Japan) not on server (RESOLVED)

### ISSUE THREAD

**Issue by HoveringHexagons** [WiiLink24/WiiLink24-Patcher#73]
The .delta isn't on the server, so the patcher fails each time.

https://patcher.wiilink24.com/forecast/Forecast_1_Wii_USA.delta

**Comment by PablosCorner** [comment]
Yeah, changes are being made to the Forecast patches, and a new patcher release will use the new links.

**Comment by PablosCorner** [comment]
Fixed in v1.2.0
