### ISSUE TITLE
(what is backspace supposed to do here exactly?)

### ISSUE THREAD

**Issue by Naim2000** [WiiLink24/WiiLink24-Patcher#74]
![image](https://github.com/WiiLink24/WiiLink24-Patcher/assets/44107089/fe72b55c-412d-4fdb-941a-11a57fbae20d)

**Comment by PablosCorner** [comment]
To go back a page.

**Comment by Naim2000** [comment]
Sorry, OBS did not want to remux this for whatever reason, but it doesn't seem to like me

https://github.com/WiiLink24/WiiLink24-Patcher/assets/44107089/bae1f577-e60b-45cc-a9e5-3fa032da42f7

**Comment by PablosCorner** [comment]
Huh... well, I'll look into that.

**Comment by PablosCorner** [comment]
Alright after looking at the code, I realized what the issue was, and I literally forgot to have it return the number it's supposed to return, so that's fixed now. Will be in v1.2.1.

**Comment by PablosCorner** [comment]
Decided to quickly fix it and reupload it for v1.2.0, so fix is live 🙌🏼
