### ISSUE TITLE
Issues with downloading

### ISSUE THREAD

**Issue by IceBlueLugia** [WiiLink24/WiiLink24-Patcher#75]
Hi, I just downloaded the newest release but when I do express installation I just get an unhandled exception error. If I do a custom installation, it downloads fine, but the Wii Room and Print channels aren't in English. Damae is in English though. I tried downloading both the vWii and Wii versions and the same thing happens. What can I do?
![image_2023-07-20_162713503](https://github.com/WiiLink24/WiiLink24-Patcher/assets/82046128/561b557c-6f52-41d3-8bbc-29d0f2f8b756)

**Comment by PablosCorner** [comment]
Try redownloading it, I just reuploaded the executables with this issue fixed.

**Comment by IceBlueLugia** [comment]
It worked! Thank you!!
