### ISSUE TITLE
Internet connection issue in vWii

### ISSUE THREAD

**Issue by myeuropeanPAL** [WiiLink24/WiiLink24-Patcher#76]
Hello, during my troubleshooting I realized that the issue is most probably with the Wifi connection of the vWii, but I would like to report it here as well only for reference.

So I installed Priiloader_v0_10RC3 on my vWii and followed this guide: https://www.wiilink24.com/guide/2installation

However when I sarted for example the Forecast Channel I got the following error message:
WiiConnect24 Standby Connection is currently turned off, so this channel cannot be used. Error Code: 109107

Now I redid the whole process a couple of days later and even synced the time with Wii U Time Sync, but I still got this error message. Fix NWC24iSetUniversalTime and Always enable WiiConnect24 for vWii were set to enabled.

Not sure what I was missing, but it seemed the vWii was not able to connect to the Wifi even though the WiiU was. The DNS was set to 167.86.108.126, I resarted my router as well, but it made no difference. In the Homwbrew channel it said Network not initialized.
Is there a solution for this or the LAN adapter is the only way?

**Comment by Naim2000** [comment]
109107 means the EULA isn't accepted. Have you dealt with that over in Wii U mode

**Comment by myeuropeanPAL** [comment]
Not sure, how do i do that? I checked the WiiU sytem settings but could not find anything about End
User Licene Agreemet, only "View Important Infoormattion and Privacy Policy". I was on systemmenu 5.5.1E, updated to 5.5.5E, but that didn't make any difference.

**Comment by PablosCorner** [comment]
v2.0.0 bundles the EULA channel for vWii users, so try that and let us know if it works

**Comment by myeuropeanPAL** [comment]
> v2.0.0 bundles the EULA channel for vWii users, so try that and let us know if it works

Hello, I installed the EULA channel, now I have the Wii Menu Electronical Manuel, where in th Q/A it says:
Can WiiConnectt24 be used?
WiiConnect24 is not supported. In addition, Wii Channels which use WiiConnect24 (such as the News Channel, the Forecast Channel and the Nintendo Channel) are also no supported.

![IMG_20240105_172609](https://github.com/WiiLink24/WiiLink24-Patcher/assets/73405825/564d867d-473e-4f09-a359-c790cbddb9b7)

Fix NWC24iSetUniversalTime and Always enable WiiConnect24 for vWii are still set to enabled with Priiloader 0.10.0 : Version Kappa.

Btw the wifi still does not work in vWii for the Homebrew channel at least, but a LAN adapter works just fine.

I also noticed a different error message in YAWM: "Couldn't find the region of this system"
Might be because of the region free setting in priiloader?

**Comment by Ingunar** [comment]
> Hello, I installed the EULA channel, now I have the Wii Menu Electronical Manuel, where in th Q/A it says: Can WiiConnectt24 be used? WiiConnect24 is not supported. In addition, Wii Channels which use WiiConnect24 (such as the News Channel, the Forecast Channel and the Nintendo Channel) are also no supported.
- The EULA channel and the Manual channel are two different things. The Manual is not important at all.

> Fix NWC24iSetUniversalTime and Always enable WiiConnect24 for vWii are still set to enabled with Priiloader 0.10.0 : Version Kappa.
- You need Permanent **vWii System Settings** not **Always enable WiiConnect24**. 
Redownload the [hacks_hash.ini](https://github.com/DacoTaco/priiloader/releases/download/0.10.0/hacks_hash.ini) again if you are missing that hack.

> Btw the wifi still does not work in vWii for the Homebrew channel at least, but a LAN adapter works just fine.

- Read [**THIS**](https://github.com/DacoTaco/priiloader/blob/master/docs/FAQ.md#how-to-use-permanent-wii-system-settings-on-vwii) to understand the vWii Settings and what you can do.

> I also noticed a different error message in YAWM: "Couldn't find the region of this system"
Might be because of the region free setting in priiloader?

- YAWM bug, already reported, just ignore it.

**Comment by myeuropeanPAL** [comment]
Somehow the "Permanent vWii System Settings" would not show up for me even after downloading a new hacks_hash.in file, so I uninstalled priiloader and instttalled it back, now everything is there.

EULA is successfully installed now with system-channel-restore.

Changed the primary DNS to 167.235.229.36, the connection test was successful, but I sill get the error message Unnable to connect to the Internet after choosing Yes here: Would you like to use the Wii Shop Channel and WiiConnect24 to the internet
error code: 221001

The bug in YAWNM seems to be fixed now.

**Comment by AyeItsHarry** [comment]
# 221001
Try changing your Wii’s country setting (for European Wiis, “United Kingdom” is recommended). If it succeeds, you can use AnyGlobe Changer to switch back to your country.
