### ISSUE TITLE
Connection Issue with Patcher

### ISSUE THREAD

**Issue by ryderflyder** [WiiLink24/WiiLink24-Patcher#77]
I'm currently trying to patch the WADs for WiiLink usage on a Wii U console, and have been receiving this error:

ERROR DETAILS:

 * Task:  Downloading 000100014843494a
 * Message: Unable to verify any online NUS server!
 * Exit code: -2146233088
 
 Not sure if this is the best way to go about reporting this, but I'm hoping this is the correct place to submit it.

**Comment by PablosCorner** [comment]
Hm, yeah I just tried it on my end and I'm getting the same error. I'll need to see if NUS is down or something.

**Comment by PablosCorner** [comment]
Looks like NUS is back online, try it again.

**Comment by ryderflyder** [comment]
Seems like things are working! I'll close this issue now.

**Comment by D4yMan** [comment]
> Looks like NUS is back online, try it again.

I seem to be getting this issue as well but I don't know how to check if its up or not. Could you send the URL to the website I should use or something?
