### ISSUE TITLE
please make android wiilink patcher or make a homebrew application wiilink patcher

### ISSUE THREAD

**Issue by Selvenity** [WiiLink24/WiiLink24-Patcher#78]
this is a thing i'll need cause i don't use pc much

**Comment by Naim2000** [comment]
Termux

**Comment by Selvenity** [comment]
i cant do it there, it hates me to death

**Comment by korbosoft** [comment]
Then you can't use the patcher. there's no other way, and there (probably) never will be.

**Comment by Selvenity** [comment]
idiot i have a PC now so i can
