### ISSUE TITLE
Gives Me Freeze of death

### ISSUE THREAD

**Issue by RunnerBoy51627** [WiiLink24/WiiLink24-Patcher#84]
im using a dolphin emulator using a japanese wii version 4.3, and everytime when i start up.
it just gives me a freeze of death

https://github.com/WiiLink24/WiiLink24-Patcher/assets/84813302/93b81152-566b-430e-a5b9-d2864fad2c60

**Comment by Naim2000** [comment]
The JPN Everybody Votes Channel WAD is broken for some reason. It's ever so fortunate to have a hash mismatch so it doesn't install on real Wiis
