### ISSUE TITLE
You cannot select your boot drive

### ISSUE THREAD

**Issue by kmannumber1** [WiiLink24/WiiLink24-Patcher#85]
I tried to select my SD card (formatted as ExFAT) in the patcher but it said "You cannot select your boot drive!".

**Comment by Naim2000** [comment]
What platform?
Your SD card can't be formatted to exFAT by the way.

**Comment by kmannumber1** [comment]
Mac, also it is now formatted to MS-DOS (FAT).

**Comment by kmannumber1** [comment]
Update: I have found that I can download to my computer so I did that.
