### ISSUE TITLE
Manually selecting a volume for the SD/HDD drive doesn't work, thinks it's pointing to the boot drive

### ISSUE THREAD

**Issue by mintasso** [WiiLink24/WiiLink24-Patcher#86]
<img width="682" alt="Screenshot 2023-12-31 at 22 36 05" src="https://github.com/WiiLink24/WiiLink24-Patcher/assets/124442838/9492bfcf-feb0-43f5-90ed-dee97e060d64">

**Comment by PablosCorner** [comment]
I'm aware of this, I did attempt a fix that should be going up in the next nightly build, I'll update here when it's out.

**Comment by PablosCorner** [comment]
If you can compile the nightly repo, try seeing if you still get this issue now.

**Comment by PablosCorner** [comment]
Should be fixed as of v2.0.0
