### ISSUE TITLE
ITS A VIRUS AVAST PUT IN IN QUARTINENE ITS FILEREP MALWARE [MISC]

### ISSUE THREAD

**Issue by ASDFFounder2015** [WiiLink24/WiiLink24-Patcher#87]
ITS A VIRUS AVAST PUT IN IN QUARTINENE ITS FILEREP MALWARE [MISC]

**Comment by Naim2000** [comment]
avast is trash btw
![ballin](https://github.com/WiiLink24/WiiLink24-Patcher/assets/44107089/054c9473-f052-4664-bf84-c1911edcd456)

**Comment by ASDFFounder2015** [comment]
SHUT UP NOW IT A VIRUUUUUUUUUUUUUUUUUUUUSSSSSSSSSSSSSSSSSSSSSS[image:
Screenshot 2024-01-04 190138.png]
EXPLAIN THIS
