### ISSUE TITLE
Everybody Votes Channel cannot install to my Wii

### ISSUE THREAD

**Issue by tesmite** [WiiLink24/WiiLink24-Patcher#88]
I was using RiiConnect24 on my Japanese Wii for several channels, including the Everybody Votes Channel.
Then WiiLink24 and RiiConnect24 were integrated and a new Patcher v2.0.0 was released, so I updated to that version and the other channels installed fine, but the Everybody Votes Channel (Japanese version) was the only one that failed to install with an Error -1022 in Content#25.
Uninstalling and reinstalling the old version of the channel did not change the problem, while the old version could still be installed.

**Comment by tesmite** [comment]
I noticed that "Fix Error Codes" for this channel, currently pointed out on the WiiLink site, refers to this problem.
Please close this issue if you do not need it.

**Comment by korbosoft** [comment]
You can also close issues.

**Comment by Naim2000** [comment]
It is needed though. The JP EVC wad is legitimately broken

**Comment by AyeItsHarry** [comment]
this has been fixed with patcher v2.0.5
