### ISSUE TITLE
"Error: (-1022) Content did not match hash in TMD." Cannot install Digicam Print Channel.

### ISSUE THREAD

**Issue by CaptainU12** [WiiLink24/WiiLink24-Patcher#9]
Okay, I've tried installing the Digicam Print Channel twice, but it comes up with this error:

"Installing content #24...Error: (-1022) Content did not match hash in TMD. Try with AHBPROT mode or an IOS with the correct permissions."

I will try using another mod manager, and I will close this issue if it works. I'm just wondering, is there a certain IOS that has to be used while installing this channel? Why does this happen?

**Comment by CaptainU12** [comment]
P.S. I am using WiiMod Lite

**Comment by KcrPL** [comment]
Hey, 

Before installing please press - and then A to uninstall the channel from console's memory and then try installing it normally. Perhaps you had it installed some time in the past.

Cheers.

**Comment by SketchMaster2001** [comment]
Closing because this is the proper fix.

**Comment by CaptainU12** [comment]
Yup! that worked. Thanks!

**Comment by KcrPL** [comment]
> Yup! that worked. Thanks!

Glad to hear that :)
