### ISSUE TITLE
Add additional Channels that are available on RiiConnect24 Patcher

### ISSUE THREAD

**Issue by larsenv** [WiiLink24/WiiLink24-Patcher#91]
RiiConnect24 Patcher has additional Channels that you can install. Even though @PablosCorner wants to add that feature, I thought it would be useful to have a GitHub issue on this to keep track of it. The additional Channels that are not available on the WiiLink Patcher as of now are the Photo Channel 1.1, Today and Tomorrow Channel, Internet Channel, and Wii Speak Channel (if WiiLink WFC will support it, ideally there could still be a Wiimmfi option). 2 other things that I would add are the ability to patch the Mii Channel with a mod to include custom symbols which is useful for Mario Kart Wii, look up Mii Channel Symbols if you want to find it. Another thing is to patch Open Shop when it comes out.

**Comment by Itsamejonah** [comment]
Wii speak channel is done, cross that out

**Comment by AyeItsHarry** [comment]
no it isn't?

**Comment by Itsamejonah** [comment]
soz for lying on accident

**Comment by AyeItsHarry** [comment]
this has been completed with v2.0.5
