### ISSUE TITLE
Issue with the WebClient

### ISSUE THREAD

**Issue by NacklessK** [WiiLink24/WiiLink24-Patcher#97]
I don't know what happened but the downloasing stopped and this popped up.

ERROR DETAILS:

 * Task:  Downloading 0001000148415450
 * Message: Downloading Content Failed:
An exception occurred during a WebClient request.
 * Exit code: -2146233088

**Comment by Megaloading** [comment]
Free up some space on your drive or if you have not selected a drive at the start select one.

**Comment by NacklessK** [comment]
It worked ! thanks !
