### ISSUE TITLE
Add region select (wiilink).wad again

### ISSUE THREAD

**Issue by Armandprogame** [WiiLink24/WiiLink24-Patcher#99]
Hello, I ask you to read again in the next update of the patcher region select (wiilink).wad for vwii users

**Comment by Armandprogame** [comment]
Because with this .wad file I was very well, it worked and I didn't need the anyglobe changer. of course I know that it is only working for those who have the wii or vwii in the regions supported by nintendo but at least make a complete offer

**Comment by AyeItsHarry** [comment]
this has been adressed in #120
